### ISSUE TITLE
Retail Store - Current: Touching Lex. Consultant skips video, goes directly to Assessment

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#16]
Build: 1.0.1
Floor plan: Retail Store - Current State
Hotspot: RC-27 (Lexmark Consultant video)

Touching RC-27 hotspot skips video and goes directly to Assessment screen. Navigating back to current state of Retail Store and re-touching RC-27 results in normal sequence of video first, then Assessment screen.

Unable to reproduce.

**Comment by nathansizemore** [comment]
All consultant touch events use the same code file.  If it were a bug, it would happen across all of them.  
This is due to the touch screen drivers.  If the touch is slow enough, it will be interpreted twice, which the first click results in the bringing up the assessment video, and the second dismissing it.  Delays between clicks and double click detection can be configured on the PC the screen is running on.

**Comment by John-McDaniel** [comment]
Interesting thing is that the screen freezes with a single frame of the video showing (forgot to mention the video freeze). It does not progress directly to the Assessment screen the way it would if dismissed typically. Happened again today on another industry. I'm willing to chalk it up to the system I'm using to review being a little underpowered, though it's holding up pretty well. We'll see if the client triggers it on the installed system and reports the issue. I'll be on site tomorrow and will attempt to create the freeze.

**Comment by nathansizemore** [comment]
Application freezes, or just the video freezes and then slides up?

**Comment by jon-powell** [comment]
@nathansizemore just the video freezes and then slides up. application is still functional.

**Comment by julius-jackson** [comment]
Resolved
